In [47]:


import pandas as pd
import numpy as np

In [48]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [49]:
movies = movies.merge(credits, on='title')

In [50]:
movies = movies[['movie_id', 'genres', 'keywords', 'title', 'overview', 'cast', 'crew']]

In [51]:
movies.isnull().sum()

movie_id    0
genres      0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [52]:
movies.dropna(inplace = True)

In [53]:
movies.duplicated().sum()

0

In [54]:
# !pip install pip
import ast
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [55]:
movies['genres'] = movies['genres'].apply(convert)

In [56]:
import ast
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [57]:
movies['keywords'] = movies['keywords'].apply(convert)

In [58]:
import ast
def convert_cast(obj):
  counter = 0
  L = []
  for i in ast.literal_eval(obj):
      if counter!=3:
        L.append(i['name'])
      else:
           break
  return L

In [59]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [60]:
import ast
def convert_crew(obj):
  L = []
  for i in ast.literal_eval(obj):
       if i['job'] == "Director":
         L.append(i['name'])
         break
  return L

In [61]:
movies['crew'] = movies['crew'].apply(convert_crew)

In [62]:
movies.head(1)

movie_id                                         genres   
0     19995  [Action, Adventure, Fantasy, Science Fiction]  \

                                            keywords   title   
0  [culture clash, future, space war, space colon...  Avatar  \

                                            overview   
0  In the 22nd century, a paraplegic Marine is di...  \

                                                cast             crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...  [James Cameron]

In [63]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [64]:
movies.head(1)

movie_id                                         genres   
0     19995  [Action, Adventure, Fantasy, Science Fiction]  \

                                            keywords   title   
0  [culture clash, future, space war, space colon...  Avatar  \

                                            overview   
0  [In, the, 22nd, century,, a, paraplegic, Marin...  \

                                                cast             crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...  [James Cameron]

In [65]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "_") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "_") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "_") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "_") for i in x])

In [66]:
movies.head(1)

movie_id                                         genres   
0     19995  [Action, Adventure, Fantasy, Science_Fiction]  \

                                            keywords   title   
0  [culture_clash, future, space_war, space_colon...  Avatar  \

                                            overview   
0  [In, the, 22nd, century,, a, paraplegic, Marin...  \

                                                cast             crew  
0  [Sam_Worthington, Zoe_Saldana, Sigourney_Weave...  [James_Cameron]

In [67]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [68]:
new_data = movies[['movie_id','title', 'tags']]

In [69]:
new_data['tags'] = new_data['tags'].apply(lambda x:" ".join(x))

C:\Users\vidit\AppData\Local\Temp\ipykernel_14940\1721321825.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags'] = new_data['tags'].apply(lambda x:" ".join(x))


In [70]:
new_data.head(1)

movie_id   title                                               tags
0     19995  Avatar  In the 22nd century, a paraplegic Marine is di...

In [71]:
new_data['tags'] = new_data['tags'].apply(lambda x:x.lower())

C:\Users\vidit\AppData\Local\Temp\ipykernel_14940\2492974546.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags'] = new_data['tags'].apply(lambda x:x.lower())


In [72]:
new_data.head(1)

movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [73]:
!pip install nltk
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

                                              0.0/1.5 MB ? eta -:--:--
     --                                       0.1/1.5 MB 2.6 MB/s eta 0:00:01
     -------                                  0.3/1.5 MB 3.3 MB/s eta 0:00:01
     ------------------                       0.7/1.5 MB 6.4 MB/s eta 0:00:01
     ------------------------------------     1.4/1.5 MB 8.8 MB/s eta 0:00:01
     ---------------------------------------  1.5/1.5 MB 9.4 MB/s eta 0:00:01
     ---------------------------------------  1.5/1.5 MB 6.8 MB/s eta 0:00:01
     ---------------------------------------- 1.5/1.5 MB 6.0 MB/s eta 0:00:00
                                              0.0/96.6 kB ? eta -:--:--
     ---------------------------------        81.9/96.6 kB ? eta -:--:--
     ---------------------------------        81.9/96.6 kB ? eta -:--:--
     ---------------------------------        81.9/96.6 kB ? eta -:--:--
     -------------------------------------- 96.6/96.6 kB 553.5 kB/s eta 0:00:00
            

In [74]:
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))
  
  return " ".join(y)

In [75]:
new_data['tags'] = new_data['tags'].apply(stem)

C:\Users\vidit\AppData\Local\Temp\ipykernel_14940\1214595124.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags'] = new_data['tags'].apply(stem)


In [83]:
!pip install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [84]:
vectors = cv.fit_transform(new_data['tags']).toarray()

In [85]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [86]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [87]:
new_data.head(1)

movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [88]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [89]:
similarity[0]

array([1.        , 0.06819943, 0.07624929, ..., 0.04357102, 0.        ,
       0.        ])

In [90]:
def recommendation(movie):
  movie_index = new_data[new_data['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse = True, key=lambda x:x[1])[1:6]
  
  for i in movies_list:
    print(new_data.iloc[i[0]].title)

In [91]:
recommendation('The Dark Knight')

Batman Begins
The Dark Knight Rises
Batman Returns
Batman Forever
Gangster's Paradise: Jerusalema


In [94]:
import pickle

In [95]:
pickle.dump(new_data.to_dict(),open('movie_dict.pkl', 'wb'))

In [96]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))